{% set name = "reladiff" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/reladiff-{{ version }}.tar.gz
  sha256: 5d392af40c771305487321fad375769312d3d4adbfab0cd5b56675f3ab50df77

build:
  entry_points:
    - reladiff = reladiff.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - runtype >=0.5.0
    - dsnparse
    - click >=8.1
    - rich
    - toml >=0.10.2
    - sqeleton >=0.1.6,<0.2.0
  run_constrained:
    - mysql-connector-python >=8.0.29
    - psycopg2 *
    - snowflake-connector-python >=2.7.2
    - cryptography *
    - trino-python-client >=0.314.0
    - presto-python-client *
    - clickhouse-driver *
    - duckdb >=0.6.0

test:
  imports:
    - reladiff
  commands:
    - pip check
    - reladiff --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/erezsh/reladiff
  doc_url: https://reladiff.readthedocs.io/
  summary: Command-line tool and Python library to efficiently diff rows across two different databases.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
